sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo curl -L -o /usr/local/bin/dobi "https://github.com/Intersections/dobi/releases/download/v0.9.1/dobi-$(uname -s)"; sudo chmod +x /usr/local/bin/dobi

script:
  - dobi
