version: '2.0'
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  influxdb:
      image: influxdb:1.3
      container_name: influx
      ports:
        - "8086:8086"
